apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-train-v12
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command:
            - "python"
          args:
            - "-m"
            - "spanet.train"
            - -of
            - "/hhh-vol/options_files/hhh_v12.json"
            - -l
            - "/hhh-vol/logs/"
            - -n
            - "v12_output"
            - --epochs
            - "2000"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 64Gi
              cpu: "16"
              nvidia.com/gpu: "1"
            requests:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/ucsd-hep-ex/hhh
            - -b
            - main
            - --recurse-submodules
            - /opt/repo/hhh
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
